//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.08 at 11:52:11 PM CEST 
//


package eu.sii.pl.sakilaapp.soap.film;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FilmDetails" type="{http://soap.sakilaapp.pl.sii.eu/film}FilmDetails"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "filmDetails"
})
@XmlRootElement(name = "GetFilmDetailsResponse")
public class GetFilmDetailsResponse {

    @XmlElement(name = "FilmDetails", required = true)
    protected FilmDetails filmDetails;

    /**
     * Gets the value of the filmDetails property.
     * 
     * @return
     *     possible object is
     *     {@link FilmDetails }
     *     
     */
    public FilmDetails getFilmDetails() {
        return filmDetails;
    }

    /**
     * Sets the value of the filmDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilmDetails }
     *     
     */
    public void setFilmDetails(FilmDetails value) {
        this.filmDetails = value;
    }

}
