//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.09 at 12:34:19 AM CEST 
//


package eu.sii.pl.sakilaapp.soap.film;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.sii.pl.sakilaapp.soap.film package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.sii.pl.sakilaapp.soap.film
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetFilmRequest }
     * 
     */
    public GetFilmRequest createGetFilmRequest() {
        return new GetFilmRequest();
    }

    /**
     * Create an instance of {@link GetFilmDetailsResponse }
     * 
     */
    public GetFilmDetailsResponse createGetFilmDetailsResponse() {
        return new GetFilmDetailsResponse();
    }

    /**
     * Create an instance of {@link FilmDetails }
     * 
     */
    public FilmDetails createFilmDetails() {
        return new FilmDetails();
    }

    /**
     * Create an instance of {@link Actor }
     * 
     */
    public Actor createActor() {
        return new Actor();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

}
