//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.08 at 11:52:11 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://soap.sakilaapp.pl.sii.eu/film", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.sii.pl.sakilaapp.soap.film;
